#pragma once

#include "willdhorn.h"

enum custom_keycodes {
  // UTILITY KEYS
  KC_EMPTY = EZ_SAFE_RANGE,
  KC_CLEAR_MODS,
  // PERSISTANT DEFALT LAYER
  KC_QWERTY,
  KC_COLEMAK_DH,
  KC_ISRT,

  // MACRO KEYS
  MCR_NEQL,
  MCR_PRNS,
  MCR_BRCS,
  MCR_CBRS,
  MCR_TILD,

  // CUSTOM ONE SHOT MODS
  KC_OSM_CMD,
  KC_OSM_SFT,
  KC_OSM_ALT,
  KC_OSM_CTL,
  // RGB
  KC_LAYERCOLOR,
  KC_LED_INC_BRGT,
  KC_LED_DCR_BRGT,
  // VSCODE
  VSC_MV_EDTR_LFT,   // MOVE EDITOR TO LEFT GROUP
  VSC_MV_EDTR_RGT,   // MOVE EDITOR TO RIGHT GROUP
  VSC_FCS_G_PREV,    // FOCUS ON PREVIOUS GROUP
  VSC_FCS_G_NEXT,    // FOCUS ON NEXT GROUP
  VSC_MV_EDTR_G_LFT, // MOVE EDITOR GROUP LEFT
  VSC_MV_EDTR_G_RGT, // MOVE EDITOR GROUP RIGHT
  VSC_OPN_DEF_SIDE,  // OPEN DEFINITION IN OPPOSITE GROUP
  // LAYER SWITCHING
  LAYER_FN_DEF,
  LAYER_FN_EXT,
  LAYER_FN_SYM,
  LAYER_FN_SYMSWAP,
};
